### ISSUE TITLE
您好,我想问下,你这个以前的hexo可以做语言切换吗?

### ISSUE THREAD

**Issue by glm196901** [zyzyz/hexo-generator-index-multi-lang#1]
我想接着你的这个继续做做多语言切换

**Comment by zyzyz** [comment]
@glm196901  
您好，我的[博客](https://zyzyz.github.io/zh-cn/terms-of-use/)已经基于整合了本插件的另一个我写的插件实现了站点多语言切换。
由于hexo本身对多子根站点的链接生成的支持并不好，本插件仅仅是弥补了其中一小部分，更多的工作实际上是在修改theme上而不是使用插件。如果可以的话可以询问一下您的思路吗？

For non-Chinese speakers:
Greetings, My [blog](https://zyzyz.github.io/en/terms-of-use/) has achieved multi-language switch by use my another plugin with this plugin integrated.
Due to the Hexo's poor support of url generating for a multi-sub-root site, this plugin only covers a little part, more modification should be done on theme rather than using plugin. If possible may I ask your thought of implementation?

**Comment by glm196901** [comment]
哈，抱歉，我也是想询问你的，语言切换的话，如果是静态文件要准备渲染的md
文档其实参考mkdocs的实现方式，把所有的文章翻译一遍，然后放在不同的XX.md中，在用户点击语言切换的的时候进行前端渲染

2018-04-03 23:28 GMT+08:00 zyzyz <notifications@github.com>:

**Comment by zyzyz** [comment]
@glm196901 
由于我并不从事web相关行业，可能也没法给出好的建议。如果你提到的“点击语言切换的时候进行前端渲染”是指点击时实时渲染，那么这并不是我目前的做法。我的实现是对1篇文章手写3份md，并在Front Matter上添加lang属性，然后使用本插件根据lang归类文章并生成对应index页。至于切换我也仅仅是在对应主题的模板上手动加了一个select用于修改url中lang部分并跳转到已渲染好的对应静态html上。

然而除此之外各主题上还存在大量的按钮跳转，为了能正确地在同一语言内跳转只有去针对具体主题的模板代码进行修改。而这不是通用性问题，没法用一个插件解决。

**Comment by glm196901** [comment]
是的，还有个比较生硬的做法就是挂前端的翻译api，但是这个感觉翻译出来的东西没什么意义，我空了想想看怎么可以做做这个事情，希望与您能继续沟通

在 2018年4月10日 下午11:00，zyzyz <notifications@github.com>写道：

**Comment by zyzyz** [comment]
@glm196901 
感谢您的青睐，对本项目的扩展和对本人博客多语言的具体实现有疑问可以随时联系。
